name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  pack-and-publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # MinVer needs tags

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-build -c Release

      - name: Pack
        run: dotnet pack src/SystemCommandLine.ConfigBinder/SystemCommandLine.ConfigBinder.csproj -c Release -o artifacts --no-build

      - name: Publish to GitHub Packages
        run: |
          for pkg in artifacts/*.nupkg; do
            echo "Publishing $pkg to GitHub Packages";
            dotnet nuget push "$pkg" --source https://nuget.pkg.github.com/roelvandersteen/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
          done

      - name: Release summary
        run: |
          echo "Package published to GitHub Packages!"
          echo "Install with: dotnet add package SystemCommandLine.ConfigBinder --source https://nuget.pkg.github.com/roelvandersteen/index.json"